default: &default
  adapter: postgresql
  encoding: unicode
  pool: 100
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: 127.0.0.1
  timeout: 5000
  port: 5432


development:
  <<: *default
  database: <%= ENV["DB_NAME"] || "postgres" %>

test:
  <<: *default
  database: <%= ENV["DB_TEST_NAME"] || "test" %>
